title: Yeo Bi (YB) Choi # your name (or website title) here
logo: "/images/yb.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a graduate student at Psychological & Brain Sciences at Dartmouth College working with Dr. Caroline Robertson. 
 
  <br><br>
  Before coming to Hanover, I completed my B.A. at the University of Chicago in Psychology and Economics. 

  <br><br>
  <a href="https://www.linkedin.com/in/yeobichoi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
